name: skillconnect
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0  # For custom fonts
  lottie: ^3.1.2       # For animated loading indicator
  animated_text_kit: ^4.2.2  # For animated text

  shimmer: ^3.0.0
  # http: ^0.15.0

  # image_picker: ^0.8.7+4
  # flutter_staggered_grid_view: ^0.4.1
  # flutter_slidable: ^1.0.0
  # carousel_slider: ^4.2.1
  # fluttertoast: ^8.2.1
  # url_launcher: ^6.1.10
  # dio: ^5.2.1
  # firebase_core: ^2.16.0
  # firebase_auth: ^6.0.0

  # firebase_messaging: ^14.0.0

  badges: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
